
# =============================================================================
# FLAKE 8 & Coverage
# =============================================================================

[flake8]
max-line-length = 80
per-file-ignores = resokit/io/io.py:A005, resokit/io/__init__.py:A005

[tox]
envlist = 
    style, 
    docstyle, 
    check-manifest, 
    coverage,
    make-docs,
    python3.10, 
    python3.11, 
    python3.12,
    python3.13

# =============================================================================
# CONF
# =============================================================================

#[pytest]
#addopts = -n "auto"

# =============================================================================
# ENVS
# =============================================================================

[testenv]
usedevelop = True
deps =
    pytest
    pytest-mock  # for the mocker fixture
commands =
    pytest -v tests/ {posargs}

[testenv:style]
skip_install = True
usedevelop = False
deps = 
    flake8
    flake8-bugbear
    flake8-import-order
    flake8-black
    flake8-builtins
    pep8-naming
commands =
    flake8 setup.py tests resokit {posargs}

[testenv:docstyle]
skip_install = True
deps =
    pydocstyle
    tomli
commands =
    pydocstyle resokit --convention=numpy {posargs}

[testenv:check-manifest]
skip_install = True
usedevelop = False
deps =
    check-manifest
commands =
    check-manifest

[testenv:coverage]
deps =
    pytest-cov
    pytest-mock  # for the mocker fixture
    coverage
commands =
    - coverage erase
    - pytest -v tests/ --cov=resokit --cov-append --cov-report term-missing --cov-report=term:skip-covered {posargs}
    coverage report --fail-under=40 -m

[testenv:make-docs]
description = "Invoke sphinx-build to build th HTML docs"
usedevelop = True
skip_install = False
changedir = docs
deps =
    -r {toxinidir}/docs/requirements.txt
commands =
    sphinx-build -W -b html -d {envtmpdir}/doctrees source {envtmpdir}/html
